name: Matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [6,8,10]
      fail-fast: true
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v
   